//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoes_shop.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public string Article { get; set; }
        public Nullable<int> NameId { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
        public int StockQuantity { get; set; }
        public string Description { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual ProductNamesDict ProductNamesDict { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
